// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_DATABASE_URL for migrations, fallback to DATABASE_URL for queries
    url: env("DIRECT_DATABASE_URL") || env("DATABASE_URL"),
  },
});
